# Generated by Django 2.1.5 on 2019-02-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190224_1652'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='blog_category',
        ),
    ]
