# Generated by Django 2.1.5 on 2019-02-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190224_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='article2tag',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='articledetail',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='articleupdown',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(default='photo/default.png', upload_to='photo/', verbose_name='头像'),
        ),
        migrations.AlterModelTable(
            name='articleupdown',
            table='',
        ),
    ]
