# Generated by Django 2.1.5 on 2019-02-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190224_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(default='photo/default.jpg', upload_to='photo/', verbose_name='头像'),
        ),
    ]
